import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://blog.smarttv.one',
  integrations: [
    mdx(),
    // sitemap generated by postbuild script
    tailwind(),
  ],
  markdown: {
    shikiConfig: { theme: 'github-dark' },
  },
});
