import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: 'https://blog.smarttv.one',
  integrations: [
    mdx(),
    // sitemap generated by postbuild script
    tailwind(),
  ],
  markdown: {
    shikiConfig: { theme: 'github-dark' },
  },
  redirects: {
    '/blog/iptv-schweiz-legal/': '/blog/iptv-schweiz-legal-kaufen-2026/',
    // WM 2026 content retired 2026-09-22 (tournament over, zero GSC indexation/traffic on every
    // page below per data/blog_index_status_2026-09-21.json) -> homepage. Source files kept in
    // backups/2026-09-22-wm-cleanup/. Includes old aliases that pointed at these pages.
    '/blog/wm-2026-alle-teams-qualifiziert/': '/',
    '/blog/deutschland-gegner-wm-2026-gruppe/': '/',
    '/blog/wm-2026-favoriten-wer-gewinnt/': '/',
    '/blog/wm-2026-mexico-vs-south-africa-20260611/': '/',
    '/blog/wm-2026-canada-vs-bosnia-herzegovina-20260612/': '/',
    '/blog/wm-2026-south-korea-vs-czechia-20260612/': '/',
    '/blog/wm-2026-qatar-vs-switzerland-20260613/': '/',
    '/blog/wm-2026-brazil-vs-morocco-20260613/': '/',
    '/blog/wm-2026-united-states-vs-paraguay-20260613/': '/',
    '/blog/wm-2026-australia-vs-tuerkiye-20260614/': '/',
    '/blog/wm-2026-germany-vs-curaçao-20260614/': '/',
    '/blog/wm-2026-haiti-vs-scotland-20260614/': '/',
    '/blog/wm-2026-ivory-coast-vs-ecuador-20260614/': '/',
    '/blog/wm-2026-netherlands-vs-japan-20260614/': '/',
    '/blog/wm-2026-belgium-vs-egypt-20260615/': '/',
    '/blog/wm-2026-saudi-arabia-vs-uruguay-20260615/': '/',
    '/blog/wm-2026-spain-vs-cape-verde-20260615/': '/',
    '/blog/wm-2026-sweden-vs-tunisia-20260615/': '/',
    '/blog/wm-2026-iran-vs-new-zealand-20260616/': '/',
    '/blog/argentinien-wm-2026/': '/',
    '/blog/bestes-iptv-wm-2026/': '/',
    '/blog/deutschland-gegner-wm-2026/': '/',
    '/blog/deutschland-wm-2026-kader-spielplan/': '/',
    '/blog/deutschland-wm-2026-spieler-kader/': '/',
    '/blog/florian-wirtz-wm-2026/': '/',
    '/blog/jamal-musiala-wm-2026/': '/',
    '/blog/wm-2026-alle-teams/': '/',
    '/blog/wm-2026-favoriten-brasilien/': '/',
    '/blog/wm-2026-favoriten-england/': '/',
    '/blog/wm-2026-favoriten-frankreich/': '/',
    '/blog/wm-2026-favoriten-spanien/': '/',
    '/blog/wm-2026-favoriten/': '/',
    '/blog/wm-2026-kostenlos-schauen/': '/',
    '/blog/wm-2026-live-iptv/': '/',
    '/blog/wm-2026-spielorte/': '/',
    '/blog/wm-2026-spielplan/': '/',
    '/blog/wm-2026-transfermarkt-wechsel-sommer-2026/': '/',
    '/blog/wm-2026-uebertragung-deutschland/': '/',
    '/blog/wm-2026-uebertragung-oesterreich/': '/',
    '/blog/wm-2026-uebertragung-schweiz/': '/',
    '/blog/wm-2026-vorhersagen-20260616/': '/',
    '/blog/wm-2026-wer-kommt-weiter-prognose/': '/',
  },
});
